import type {
  DefaultSharedCoreModuleContext,
  LangiumCoreServices,
  LangiumSharedCoreServices,
  Module,
  PartialLangiumCoreServices,
} from 'langium';
import {
  EmptyFileSystem,
  createDefaultCoreModule,
  createDefaultSharedCoreModule,
  inject,
} from 'langium';

import {
  MermaidGeneratedSharedModule,
  TeamTopologyGrammarGeneratedModule as TeamTopologyGeneratedModule,
} from '../generated/module.js';
import { TeamTopologyTokenBuilder } from './tokenBuilder.js';
import { TeamTopologyValueConverter } from './valueConverter.js';

/**
 * Declaration of `TeamTopology` services.
 */
interface TeamTopologyAddedServices {
  parser: {
    TokenBuilder: TeamTopologyTokenBuilder;
    ValueConverter: TeamTopologyValueConverter;
  };
}

/**
 * Union of Langium default services and `TeamTopology` services.
 */
export type TeamTopologyServices = LangiumCoreServices & TeamTopologyAddedServices;

/**
 * Dependency injection module that overrides Langium default services and
 * contributes the declared `TeamTopology` services.
 */
export const TeamTopologyModule: Module<
  TeamTopologyServices,
  PartialLangiumCoreServices & TeamTopologyAddedServices
> = {
  parser: {
    TokenBuilder: () => new TeamTopologyTokenBuilder(),
    ValueConverter: () => new TeamTopologyValueConverter(),
  },
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 * @param context - Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createTeamTopologyServices(
  context: DefaultSharedCoreModuleContext = EmptyFileSystem
): {
  shared: LangiumSharedCoreServices;
  TeamTopology: TeamTopologyServices;
} {
  const shared: LangiumSharedCoreServices = inject(
    createDefaultSharedCoreModule(context),
    MermaidGeneratedSharedModule
  );
  const TeamTopology: TeamTopologyServices = inject(
    createDefaultCoreModule({ shared }),
    TeamTopologyGeneratedModule,
    TeamTopologyModule
  );
  shared.ServiceRegistry.register(TeamTopology);
  return { shared, TeamTopology };
}

export type InteractionMode = 'Collaboration' | 'Facilitation' | 'XaaS';
export type InteractionArrow = '->' | '-->';

export interface ParsedInteraction {
  lhs: string;
  mode: InteractionMode;
  arrow: InteractionArrow;
  rhs: string;
}

/**
 * Parse a raw `TT_INTERACTION_LINE` string into its structured components.
 *
 * The line has the form:  lhs--Mode->rhs  or  lhs--Mode-->rhs
 * where lhs/rhs are bare identifiers or quoted strings.
 *
 * @example
 * parseInteractionLine('f1--XaaS->f2')
 * // => { lhs: 'f1', mode: 'XaaS', arrow: '->', rhs: 'f2' }
 *
 * @example
 * parseInteractionLine('"Stream A"--Collaboration-->"Stream B"')
 * // => { lhs: 'Stream A', mode: 'Collaboration', arrow: '-->', rhs: 'Stream B' }
 */
export function parseInteractionLine(line: string): ParsedInteraction {
  // Each name is either:
  //   "double-quoted"  => group 1 (double) or group 2 (single)
  //   'single-quoted'  => group 2
  //   bareWord         => group 3 (\w+)
  // Then -- separates the name from the mode.
  // Mode is group 4 (Collaboration | Facilitation | XaaS).
  // Arrow is group 5 (--> or ->).
  // rhs name follows the same double/single/bare pattern (groups 6, 7, 8).
  const TT_NAME = /(?:"([^"]*)"|'([^']*)'|(\w+))/;
  const TT_MODE = /(Collaboration|Facilitation|XaaS)/;
  const TT_ARROW = /(-->|->)/;
  const pattern = new RegExp(
    `^${TT_NAME.source}--${TT_MODE.source}${TT_ARROW.source}${TT_NAME.source}$`
  );

  const match = pattern.exec(line);
  if (!match) {
    throw new Error(`Invalid TT interaction line: ${JSON.stringify(line)}`);
  }

  // lhs: one of double-quoted (1), single-quoted (2), or bare (3)
  const lhs = match[1] ?? match[2] ?? match[3];
  const mode = match[4] as InteractionMode;
  const arrow = match[5] as InteractionArrow;
  // rhs: one of double-quoted (6), single-quoted (7), or bare (8)
  const rhs = match[6] ?? match[7] ?? match[8];

  if (lhs === undefined || rhs === undefined) {
    // Should be unreachable given the pattern requires a name on each side
    throw new Error(`Failed to extract lhs/rhs from interaction line: ${JSON.stringify(line)}`);
  }

  return { lhs, mode, arrow, rhs };
}
