import type {
  DefaultSharedCoreModuleContext,
  LangiumCoreServices,
  LangiumSharedCoreServices,
  Module,
  PartialLangiumCoreServices,
} from 'langium';
import {
  EmptyFileSystem,
  createDefaultCoreModule,
  createDefaultSharedCoreModule,
  inject,
} from 'langium';

import {
  MermaidGeneratedSharedModule,
  TeamTopologyGrammarGeneratedModule as TeamTopologyGeneratedModule,
} from '../generated/module.js';
import { TeamTopologyTokenBuilder } from './tokenBuilder.js';
import { TeamTopologyValueConverter } from './valueConverter.js';

/**
 * Declaration of `TeamTopology` services.
 */
interface TeamTopologyAddedServices {
  parser: {
    TokenBuilder: TeamTopologyTokenBuilder;
    ValueConverter: TeamTopologyValueConverter;
  };
}

/**
 * Union of Langium default services and `TeamTopology` services.
 */
export type TeamTopologyServices = LangiumCoreServices & TeamTopologyAddedServices;

/**
 * Dependency injection module that overrides Langium default services and
 * contributes the declared `TeamTopology` services.
 */
export const TeamTopologyModule: Module<
  TeamTopologyServices,
  PartialLangiumCoreServices & TeamTopologyAddedServices
> = {
  parser: {
    TokenBuilder: () => new TeamTopologyTokenBuilder(),
    ValueConverter: () => new TeamTopologyValueConverter(),
  },
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 * @param context - Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createTeamTopologyServices(
  context: DefaultSharedCoreModuleContext = EmptyFileSystem
): {
  shared: LangiumSharedCoreServices;
  TeamTopology: TeamTopologyServices;
} {
  const shared: LangiumSharedCoreServices = inject(
    createDefaultSharedCoreModule(context),
    MermaidGeneratedSharedModule
  );
  const TeamTopology: TeamTopologyServices = inject(
    createDefaultCoreModule({ shared }),
    TeamTopologyGeneratedModule,
    TeamTopologyModule
  );
  shared.ServiceRegistry.register(TeamTopology);
  return { shared, TeamTopology };
}
